// projects actions
export const DOWNLOAD_PROJECTS = 'DOWNLOAD_PROJECTS';
export const CREATE_PROJECT = 'CREATE_PROJECT';
export const REMOVE_PROJECT = 'REMOVE_PROJECT';
export const REVIVE_PROJECT = 'REVIVE_PROJECT';

// windows actions
export const LOAD_WINDOWS = 'LOAD_WINDOWS';
export const CLOSE_TABS = 'CLOSE_TABS';
export const CLOSE_SELECTED_TABS = 'CLOSE_SELECTED_TABS';
export const ACTIVATE_TAB = 'ACTIVATE_TAB';

// quickActions actions
export const SET_QUICK_ACTION_INPUT = 'SET_QUICK_ACTION_INPUT';
export const UPDATE_SEARCH_RESULTS = 'UPDATE_SEARCH_RESULTS';
export const SELECT_FIRST_RESULT = 'SELECT_FIRST_RESULT';
export const SELECT_PREVIOUS_RESULT = 'SELECT_PREVIOUS_RESULT';
export const SELECT_NEXT_RESULT = 'SELECT_NEXT_RESULT';
export const EXECUTE_QUICK_ACTION = 'EXECUTE_QUICK_ACTION';
